### ISSUE TITLE
Flickering display and missing menu item.

### ISSUE THREAD

**Issue by lou-costello** [victorporof/Tilt#17] opened 2011-11-04 18:51 UTC
Installed Tilt 0.9.1.7 

Looked in Tools> and Tools>Web Developer for Tilt. Cannot find.
Looked in Tools>Add-ons and it is installed.
Used Ctrl+Shift+M to start, and it does start and it does display the Tilt DOM and I can manipulate it in 3D space.

So even though it can't be found in the menu, it can be used.

Unfortunately with Tilt installed the menu items now flicker terribly, to the point of being unusable. By this I mean I place the mouse cursor over the "Tools" menu item and press down. The word Tools vanishes and an empty drop down box flickers momentarily and then vanishes, leaving just a drop shadow outline. If I move the cursor down into the drop down box the information reappears, but its now very touchy. At various points the box will flicker, vanish then reappear. When the cursor moves over a menu item that has a ">" for expanding another drop down box, the selection highlight jumps upward one menu item, then back down. Sometimes the second drop down opens, sometimes it doesn't.

I have the web developer tool bar installed and the behavior here is affected as well. Basically it seems to happen to all the items in the menu bar.

If I remove Tilt, everything returns to normal (thank you for that). At this point the flickering unfortunately means I can not use this tool for the time being :(

I like Tilt and can see a tremendous benefit coming from it, particularly when you get it to the point that I can click on an item in the Tilt display and get its DOM trace, css etc. I will really help visualize the location of items for those of us learning Javascript for example.

My workspace:
Firefox 7.0.1 (latest release as of nov 14 2011)
# Installed Add-ons

Adblock Plus    1.3.10
Adblock Plus Pop-up Addon   0.2.9
AlertCheck  1.1
BetterPrivacy   1.67
ColorZilla  2.6.2.1
Console²   0.8
Context Font    0.6
DOM Inspector   2.0.10
Firebug 1.8.3
Flagfox 4.1.8
Ghostery    2.6.0.1
Google Analytics Opt-out Browser Add-on 0.9.5
GridFox 2.0
Hostname in Titlebar    2.0.0
MeasureIt   0.4.10
Screengrab  0.96.3
ShowIP  1.0
Tilt    0.9.1.7
Web Developer   1.1.9

**Comment by victorporof** [comment] 2011-11-08 17:35
Thanks for such a thorough issue report!

I tried replicating your environment, and I can't seem to get the menu flickering you're telling me about. It would be helpful if you could try installing Tilt in a clean user profile and see what happens. Details here: http://support.mozilla.com/en-US/kb/Managing-profiles

If that doesn't help, maybe you could try a Nightly or Aurora build (lots of bugs are fixed in these releases, although new ones sometimes appear): http://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/latest-trunk/ or http://www.mozilla.org/en-US/firefox/channel/

Also, what OS are you on? There are many differences between Linux, Windows or Mac, and this can be really useful to isolate the problem.

**Comment by lou-costello** [comment] 2011-11-09 19:14
Thanks for responding. I'm working on a Win 7 system.

So I followed your instructions. Created a clean profile and only installed Tilt from the Firefox add-on page. 
It worked fine. No flickering.

However, there was a change. Under Tools I now find a "Web Developer" menu item. This surprised me, since I did not add Chris Pedericks Web Developer. Within this menu item I found Tilt! Just the way it was supposed to appear. This probably sounds strange to you, but I'm guessing this is where the problem was (more later).

I began adding back in my add-ons to try to determine what went wrong. Added Firebug, Web Developer, Ad Block (with Pop up blocker), Flag Fox. No problems. One odd thing occured. I now have two "Web Developer" menu items. One has Tilt in it, and the other is Chris's.

Restarted my default profile to confirm the problem still existed there. Flickering is not only gone, but now I have two Web Developer menu items in this profile also, and Tilt now exists inside one of them. Note, I did not change this profile at all.

So positives:
Tilt now works in both profiles without flickering.
Possible solution to others who experience a similar problem is to create and use a new profile, add on Tilt, restart the new profile, check if flickering is gone. If flickering is gone then restart Firefox in the original profile and see if this solved the problem there too.

negatives:
Can't tell you what caused the problem. I hate that. My intuition says that something is going wrong with Chris Pederick's Web Developer. I don't think it is right to have two menu items in Tools called "Web Developer." The first item in the menu contains Chris's tools. The second now contains the original content from Firefox (web console, scratchpad, dom inspector etc), Firebug and now Tilt. I am going on memory here, but I believe my original system, before trying the new profile only had Chris's Web Developer in the Tools drop down, not the Firefox menu item. The original Firefox Web Developer drop down did not exist (I am almost sure of this because I recall being upset that I lost the DOM inspector at some point during the the Firefox 6,7 update process). So in the end this is probably not a Tilt issue, except you may want to check the existence of the Tools>Web Developer menu item, and that if the item exists, check that it is actually the Firefox menu item, not Chris's Web Developer menu item before attempting to add Tilt to it. This is probably why I could not find Tilt in the menu when the problem all started.

Tilt works. Can't wait for all the bells and whistles to be added.

Thanks for the help. If the flickering recurs I will update you. Just noticed Firefox wants to update to 8 so..... :)

**Comment by lou-costello** [comment] 2011-11-09 19:15
whoops, hit the wrong button. Feel free to close this issue if you wish.

**Comment by victorporof** [comment] 2011-11-09 19:38
The problem is most likely because the original Firefox Web Developer drop down did not exist. This should never have happened. You can file a bug in https://bugzilla.mozilla.org/ under Firefox and Menus, and say that the Web Developer menu disappeared when updating to Firefox 6/7, and maybe someone there can fix this (it may affect other users than you).

Thanks!

**Closed as completed by victorporof** 2011-11-09 19:38 UTC
